#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='ap-balcony'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan6=interface
  set network.lan6.proto='dhcpv6'
  set network.lan6.ifname='@lan'
  set network.lan6.reqprefix='no'

  set network.ff=interface
  set network.ff.proto='static'
  set network.ff.ifname='eth0.2'
  set network.ff.ipaddr='192.168.0.1'
  set network.ff.netmask='255.255.255.0'
  set network.ff.macaddr='C4:6E:1F:54:C6:43'
  commit network
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.3.4'
  del network.lan.ip6assign

  set network.single=interface
  set network.single.proto='static'
  set network.single.ifname='br-lan'
  set network.single.ipaddr='192.168.2.4'
  set network.single.netmask='255.255.255.255'
  commit network
EOF

exit 0
