#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='ap-balcony'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan6=interface
  set network.lan6.proto='dhcpv6'
  set network.lan6.ifname='@lan'
  set network.lan6.reqprefix='no'

  set network.ff=interface
  set network.ff.proto='static'
  set network.ff.ifname='eth0.2'
  set network.ff.ipaddr='192.168.0.1'
  set network.ff.netmask='255.255.255.0'
  commit network
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.2.4'
  del network.lan.ip6assign
  commit network
EOF

exit 0
