#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set dhcp.@dnsmasq[0].domain=dhcp.ff.home.measite.de
  set dhcp.@dnsmasq[0].local=/dhcp.ff.home.measite.de/
  delete dhcp.lan
  set dhcp.ff=dhcp
  set dhcp.ff.start=100
  set dhcp.ff.limit=254
  set dhcp.ff.leasetime=24h
  set dhcp.ff.interface=ff
  add_list dhcp.ff.dhcp_option=6,192.168.0.1,8.8.8.8
  commit dhcp
EOF
