#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.check=watchcat
  set system.check.period='1h'
  set system.check.mode='ping'
  set system.check.pinghosts='192.168.2.1'
  set system.check.forcedelay='60'
  commit system
EOF

exit 0
