#!/bin/sh
cat > /etc/config/firewall << _FIREWALL_

config defaults
        option input 'DROP'
        option output 'DROP'
        option forward 'DROP'

config include
        option path '/etc/firewall.user'

config zone
        option input 'ACCEPT'
        option forward 'ACCEPT'
        option output 'ACCEPT'
        option name 'lan'
        option network 'lan lan6 nwi_mesh0 nwi_mesh1'

config zone
        option name 'ff'
        option input 'DROP'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option network 'ff'

config rule
        option enabled '1'
        option target 'ACCEPT'
        option src 'ff'
        option proto 'all'
        option dest_port '67'
        option name 'DHCP'

config rule
        option enabled '1'
        option target 'ACCEPT'
        option src 'ff'
        option proto 'tcp udp'
        option dest_port '53'
        option name 'DNS'

config rule
        option enabled '1'
        option target 'ACCEPT'
        option src 'ff'
        option proto 'tcp udp'
        option dest_port '22'
        option name 'SSH'

config forwarding
        option dest 'lan'
        option src 'ff'

config forwarding
        option dest 'ff'
        option src 'lan'

config zone
        option input 'DROP'
        option forward 'DROP'
        option name 'ffclient'
        option masq '1'
        option network 'wan'
        option output 'ACCEPT'

config forwarding
        option dest 'ffclient'
        option src 'lan'
_FIREWALL_

uci commit firewall
