#!/bin/sh

addr=$(uci get network.lan.ipaddr)
source /etc/secrets/env

cat > /etc/bird.conf <<-EOF
log syslog all;

router id ${addr};

protocol device {
        scan time 10;
}

protocol kernel {
        learn;
        export filter {
          if 0.0.0.0 ~ net then reject;
          accept;
        };
        import all;
        debug all;
        scan time 10;
}

protocol static {
        export all;
}

protocol direct {
        export all;
}

protocol ospf {
        import filter {
          if (source = RTS_OSPF_EXT2 && net = 0.0.0.0/0) then reject;
          accept;
        };
        import all;
        export all;
        debug all;

        area 0 {
                interface "br-lan" {
                        cost 10;
                        type broadcast;
                        hello 5; retransmit 2; wait 20; dead 60;
                        authentication cryptographic; password "${ospf_pass}";
                };

                interface "wifi*" {
                        cost 50;
                        type broadcast;
                        hello 5; retransmit 2; wait 20; dead 60;
                        authentication cryptographic; password "${ospf_pass}";
                };

                interface "wlan*" {
                        cost 50;
                        type broadcast;
                        hello 5; retransmit 2; wait 20; dead 60;
                        authentication cryptographic; password "${ospf_pass}";
                };

                interface "bat0" {
                        cost 51;
                        type broadcast;
                        hello 5; retransmit 2; wait 20; dead 60;
                        authentication cryptographic; password "${ospf_pass}";
                };

                interface "wg*" {
                        cost 75;
                        type broadcast;
                        hello 5; retransmit 2; wait 20; dead 60;
                        authentication cryptographic; password "${ospf_pass}";
                };

                interface "*" {
                        cost 100;
                        stub;
                };
        };
}
EOF

/etc/init.d/bird4 restart
