#!/bin/sh

source /etc/secrets/env

add_wireless() {
  radio=$1
  ssid=$2
  pass=$3
  radioid=$(echo ${radio}|tr -d 'a-z')
uci -q batch <<-EOF >/dev/null
set wireless.${radio}_${ssid}=wifi-iface
set wireless.${radio}_${ssid}.device=${radio}
set wireless.${radio}_${ssid}.network=lan
set wireless.${radio}_${ssid}.mode=ap
set wireless.${radio}_${ssid}.encryption=psk2
set wireless.${radio}_${ssid}.auth_cache='1'
set wireless.${radio}_${ssid}.disassoc_low_ack='0'
set wireless.${radio}_${ssid}.ssid=${ssid}
set wireless.${radio}_${ssid}.key=${pass}
set wireless.${radio}_${ssid}.doth=1
set wireless.${radio}_${ssid}.ieee80211w=0
set wireless.${radio}_${ssid}.ieee80211r=1
set wireless.${radio}_${ssid}.ieee80211k=1
set wireless.${radio}_${ssid}.ieee80211v='1'
set wireless.${radio}_${ssid}.ft_psk_generate_local=1
set wireless.${radio}_${ssid}.ft_over_ds=0
set wireless.${radio}_${ssid}.mobility_domain=${wifi_mobdomain}
set wireless.${radio}_${ssid}.wnm_sleep_mode='1'
set wireless.${radio}_${ssid}.bss_transition='1'
set wireless.${radio}_${ssid}.logger_syslog_level='1'
set wireless.${radio}_${ssid}.time_advertisement='2'
set wireless.${radio}_${ssid}.time_zone='CET-1CEST-2,M3.5.0/02:00:00,M10.5.0/03:00:00'
EOF

  uci commit wireless
}

wpa3() {
  radio=$1
  ssid=$2
uci -q batch <<-EOF >/dev/null
set wireless.${radio}_${ssid}.encryption=sae-mixed
EOF
  uci commit wireless
}

add_wireless radio0 nina ${wifi_nina_key}
add_wireless radio1 nina ${wifi_nina_key}
add_wireless radio0 Strahlenkanone ${wifi_strahlenkanone_key}
add_wireless radio1 Strahlenkanone ${wifi_strahlenkanone_key}
add_wireless radio0 echelon ${wifi_echelon_key}
add_wireless radio1 echelon ${wifi_echelon_key}

wpa3 radio0 Strahlenkanone
wpa3 radio1 Strahlenkanone

exit 0
