#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='dsl'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.2.2'
  set network.lan.dns='192.168.2.5' '192.168.2.8' '192.168.2.7'
  del network.lan.ip6assign
  commit network
EOF

exit 0
