#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set wireless.radio0.country=DE
  set wireless.radio0.channel=3
  set wireless.radio0.htmode='HT20'
  set wireless.radio0.disabled=0
  delete wireless.default_radio0
  commit wireless
EOF

exit 0
