#!/bin/sh

cat > /etc/config/firewall << _FIREWALL_
config defaults
        option output 'ACCEPT'
        option input 'REJECT'
        option forward 'DROP'

config include
        option path '/etc/firewall.user'

config zone
        option name 'lan'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option masq_allow_invalid '1'
        option auto_helper '0'
        option network 'lan lan6 nwi_mesh0 wg'

config zone
        option name 'wan'
        option input 'DROP'
        option output 'ACCEPT'
        option forward 'DROP'
        option auto_helper '0'
        option network 'wan'
        option masq '1'

config forwarding
        option src 'lan'
        option dest 'wan'
_FIREWALL_

uci commit firewall
