---
packages:
  - prometheus
write_files:
  - path: /var/lib/prometheus/node-exporter/hue_meta.prom
    owner: root:root
    permissions: '0644'
    content: |
      # Power consumption per model
      # hue
      hue_light_consumption_watt{model="LLC007"} 8.0
      hue_light_consumption_watt{model="LCT001"} 8.5
      hue_light_consumption_watt{model="LCT001"} 10.0
      # innr
      hue_light_consumption_watt{model="RB 165"} 9.0
      # IKEA
      hue_light_consumption_watt{model="TRADFRI bulb E27 WS opal 980lm"} 12.0
      hue_light_consumption_watt{model="TRADFRI bulb E27 opal 1000lm"} 12.5
  - path: /etc/prometheus/prometheus.yaml
    owner: root:root
    permissions: '0644'
    content: |
      global:
        scrape_interval:     15s
        evaluation_interval: 15s
      rule_files:
        - /etc/prometheus/rules-*.yml
      scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'network-node'
        static_configs:
        - targets:
          - '192.168.2.1:9100'
          - '192.168.2.5:9100'
          - '192.168.2.5:9100'
          - '192.168.2.8:9100'
          - '192.168.3.4:9100'
      - job_name: 'node'
        static_configs:
        - targets:
          - '192.168.2.15:9100'
          - '192.168.2.28:9100'
          - '192.168.2.29:9100'
