---
packages:
  - prometheus-alertmanager
  - prometheus-bird-exporter
  - prometheus-snmp-exporter
  - prometheus-blackbox-exporter
  - prometheus
  - golang
write_files:
  - path: /etc/prometheus/prometheus.yml
    owner: root:root
    permissions: '0644'
    content: |
      global:
        scrape_interval:     15s
        evaluation_interval: 15s
      alerting:
        alertmanagers:
          - static_configs:
            - targets: ['localhost:9093']
      rule_files:
        - /etc/prometheus/rules-*.yml
      scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'network-node'
        static_configs:
        - targets:
          - '192.168.2.1:9100'
          - '192.168.2.3:9100'
          - '192.168.3.4:9100'
          - '192.168.2.5:9100'
          - '192.168.2.7:9100'
          - '192.168.2.8:9100'
          - '192.168.2.10:9100'
      - job_name: 'node'
        static_configs:
        - targets:
          - '192.168.2.16:9100'
          - '192.168.2.20:9100'
          - '192.168.2.21:9100'
          - '192.168.2.28:9100'
          - '192.168.2.29:9100'
