{
 "title": "Home",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "DSL DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=\"192.168.2.1:9100\",device=\"pppoe-wan\"}[1m])",
     "legendFormat": "bytes in"
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 } },
  {
   "title": "DSL UP",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=\"192.168.2.1:9100\",device=\"pppoe-wan\"}[1m])",
     "legendFormat": "bytes in"
    }
   ]
  },
  {
   "title": "Frequency Quality",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "quantile by (instance, frequency) (0.5, wifi_network_quality{frequency=~\"5.*\",ssid!=\"strahlenmesh\"} > 0) * on (instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "quantile by (instance, frequency) (0.5, wifi_network_quality{frequency=~\"2.*\",ssid!=\"strahlenmesh\"} > 0) * on (instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "wifi station -> client",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (rate(node_network_transmit_bytes_total{device=~\"wlan.*\"}[2m]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"ap-.*\"})",
     "legendFormat": "{{nodename}} out"
    }
   ]
  },
  {
   "title": "wifi client -> station",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (nodename) (rate(node_network_receive_bytes_total{device=~\"wlan.*\"}[2m]) * on (instance) group_left(nodename) node_uname_info{nodename=~\"ap-.*\"})",
     "legendFormat": "{{nodename}} in"
    }
   ]
  },
  {
   "title": "Signal/Noise",
   "type": "snuids-radar-panel",
   "gridPos": { "h": 9, "w": 5, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "quantile by (frequency,instance) (0.5, (wifi_network_signal_dbm > -255) -wifi_network_noise_dbm{frequency=~\"5.*\",ssid!=\"strahlenmesh\"}) * on (instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    },
    {
     "expr": "quantile by (frequency,instance) (0.5, (wifi_network_signal_dbm > -255) -wifi_network_noise_dbm{frequency=~\"2.*\",ssid!=\"strahlenmesh\"}) * on (instance) group_left(nodename) node_uname_info",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "Clients per frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 19, "x": 5, "y": 16 },
   "targets": [
    {
     "expr": "sum by (frequency) (wifi_stations * on (ifname, instance) group_left(frequency) count by (ifname, frequency, instance) (max by (ifname, frequency,instance) (wifi_network_noise_dbm{ssid!=\"strahlenmesh\"}))) > 0",
     "legendFormat": "{{frequency}}"
    }
   ]
  }
 ]
}