#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='router'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.2.1'
  set network.lan.macaddr='80:2A:A8:1E:86:A0'
  commit network
EOF

exit 0
