#!/bin/sh

source /etc/secrets/env

uci -q batch <<-EOF >/dev/null
  delete network.wan
  delete network.wan6
  delete network.@device[0]

  set network.br_lan=device
  set network.br_lan.name='br-lan'
  set network.br_lan.type='bridge'
  set network.br_lan.ports='eth0 eth1 eth2 eth3'

  # radvd / ipv6

  set network.lan.ip6assign=56

  # switch ports / brdige

  set network.lan.ifname='eth0 eth1 eth2 eth3'

  # modem management port

  set network.modem=interface
  set network.modem.proto=static
  set network.modem.ipaddr=192.168.1.2
  set network.modem.netmask=255.255.255.252
  set network.modem.device=eth4
  set network.modem.ipv6=off

  # PPPoE (eth4)

  # set network.ifwan=device
  # set network.ifwan.type=8021q
  # set network.ifwan.ifname=eth4
  # set network.ifwan.name=ifwan
  # set network.ifwan.vid=7

  # set network.ifwan_iptv=device
  # set network.ifwan_iptv.type=8021q
  # set network.ifwan_iptv.ifname=eth4
  # set network.ifwan_iptv.name=eth4.8
  # set network.ifwan_iptv.vid=8

  set network.wan=interface
  set network.wan.proto='pppoe'
  set network.wan.device='eth4'
  set network.wan.ipv6='auto'
  set network.wan.username='${telekom_user}'
  set network.wan.password='${telekom_pass}'
  set network.wan.macaddr='80:2A:A8:1E:86:B0'

  # set network.wan_iptv=interface
  # set network.wan_iptv.proto='dhcp'
  # set network.wan_iptv.ifname='ifwan_iptv'
  # set network.wan_iptv.ipv6='auto'
  # set network.wan_iptv.macaddr='80:2A:A8:1E:86:B1'

  set network.wan6=interface
  set network.wan6.device='@wan'
  set network.wan6.proto='dhcpv6'
  set network.wan6.reqprefix='56'

  set network.lan.ip6assign=56

  commit network
EOF

uci -q batch <<-EOF >/dev/null
  set dhcp.@dnsmasq[0].domain=dhcp.home.measite.de
  set dhcp.@dnsmasq[0].local=/dhcp.home.measite.de/
  set dhcp.lan.start=100
  set dhcp.lan.limit=254
  set dhcp.lan.leasetime=24h
  add_list dns=192.168.2.7,192.168.2.6,192.168.2.3
  add_list dhcp.lan.dhcp_option=6,192.168.2.7,192.168.2.6,192.168.2.3

  set dhcp.lan.ra_default='1'
  add_list dhcp.lan.dns='fe80::5ad5:6eff:fe1f:77b6'
  add_list dhcp.lan.dns='fe80::214:4fff:fefc:301'
  add_list dhcp.lan.dns='fe80::214:4fff:fefc:701'
  del dhcp.lan.ra_slaac
  commit dhcp
EOF

exit 0
