#!/bin/sh

source /etc/secrets/env

uci -q batch <<-EOF >/dev/null
  delete network.wan
  delete network.wan6
  delete network.@switch[0]
  delete network.@switch_vlan[1]
  delete network.@switch_vlan[0]

  set network.switch=switch
  set network.switch.name='switch0'
  set network.switch.reset='1'
  set network.switch.enable_vlan='1'

  set network.switch_lan=switch_vlan
  set network.switch_lan.device='switch0'
  set network.switch_lan.vlan='1'
  set network.switch_lan.ports='0 1 2 3 6t'

  set network.switch_wan_7=switch_vlan
  set network.switch_wan_7.device='switch0'
  set network.switch_wan_7.vlan='2'
  set network.switch_wan_7.vid='7'
  set network.switch_wan_7.ports='4t 6t'

  set network.switch_wan_8=switch_vlan
  set network.switch_wan_8.device='switch0'
  set network.switch_wan_8.vlan='3'
  set network.switch_wan_8.vid='8'
  set network.switch_wan_8.ports='4t 6t'

  set network.wan=interface
  set network.wan.ifname='eth0.7'
  set network.wan.proto='pppoe'
  set network.wan.ipv6='auto'
  set network.wan.username='${telekom_user}'
  set network.wan.password='${telekom_pass}'
  set network.wan.keepalive=10
  set network.wan.mtu=1500

  set network.wan_iptv=interface
  set network.wan_iptv.ifname='eth0.8'
  set network.wan_iptv.proto='dhcp'
  set network.wan_iptv.mtu=1500
  set network.wan_iptv.ipv6='auto'

  set network.wan6=interface
  set network.wan6.ifname='@wan'
  set network.wan6.proto='dhcpv6'
  set network.wan6.reqprefix='56'

  set network.lan.ip6assign=56

  commit network
EOF

exit 0
