#!/bin/sh

static_lease() {
  name=$1
  mac=$2
  ip=$3
  section=$(echo "${name}"|tr '-' '_')
uci -q batch <<-EOF >/dev/null
  set dhcp.${section}=host
  set dhcp.${section}.name=${name}
  set dhcp.${section}.mac=${mac}
  set dhcp.${section}.ip=${ip}
  commit dhcp
EOF
}

static_lease 'hue-gateway'        '00:17:88:a6:55:32' '192.168.2.30'

static_lease 'power-aquarium'     'ac:84:c6:59:ca:9f' '192.168.2.31'
static_lease 'power-tv-a'         '50:c7:bf:0b:90:e8' '192.168.2.32'
static_lease 'power-tv-b'         '50:c7:bf:0b:88:3b' '192.168.2.33'
static_lease 'power-outdoor'      '50:c7:bf:0b:8b:b0' '192.168.2.34'
static_lease 'power-kuehlschrank' '50:c7:bf:0b:8d:27' '192.168.2.35'
static_lease 'power-3d-druck'     '50:c7:bf:28:bd:d9' '192.168.2.36'
static_lease 'power-tv-c'         'ac:84:c6:28:fd:53' '192.168.2.37'
static_lease 'power-tv-d'         'ac:84:c6:29:16:34' '192.168.2.38'
static_lease 'power-washing'      'ac:84:c6:5d:9d:3d' '192.168.2.39'
static_lease 'power-dishwash'     'ac:84:c6:3b:b4:2f' '192.168.2.40'
static_lease 'power-beer'         'ac:84:c6:3b:b1:35' '192.168.2.41'
static_lease 'power-print'        'ac:84:c6:29:03:d9' '192.168.2.42'

static_lease 'sky'                 '7c:2f:80:b1:c3:1c' '192.168.2.48'
static_lease 'harmonyhub'          'c8:db:26:07:09:c2' '192.168.2.49'
static_lease 'chromecast-living'   '54:60:09:fc:0f:68' '192.168.2.50'
static_lease 'chromecast-balcony'  '54:60:09:d8:e2:1c' '192.168.2.51'
static_lease 'chromecast-bathroom' '54:60:09:e7:69:4e' '192.168.2.52'

static_lease 'phonie'             'b8:27:eb:a8:d1:01' '192.168.2.60'

static_lease 'firetv'             '60:6d:3c:0b:b8:c4' '192.168.2.80'
static_lease 'printer'            'b4:b5:2f:f5:86:7c' '192.168.2.81'
static_lease 'voip'               '7c:2f:80:b1:c3:1c' '192.168.2.82'
static_lease 'phone'              '00:0a:e2:04:0a:b9' '192.168.2.83'

static_lease 'nina-iphone'        '34:ab:37:ed:48:69' '192.168.2.90'
static_lease 'rene-android'       '94:65:2d:a5:9c:44' '192.168.2.91'
static_lease 'rts22'              'd2:47:d6:b9:a8:7e' '192.168.2.92'

static_lease 'bolt'               'dc:a6:32:f2:f3:aa' '192.168.2.20'
static_lease 'kakerlake'          'dc:a6:32:23:45:90' '192.168.2.21'

exit 0
