#!/bin/sh

source /etc/secrets/env

uci -q batch <<-EOF >/dev/null
  delete network.wg

  set network.wg=interface
  set network.wg.proto='wireguard'
  set network.wg.private_key='${WG_KEY}'
  set network.wg.listen_port=51820
  set network.wg.force_link='1'
  add_list network.wg.addresses='192.168.9.1/32'

  set network.route_wg=route
  set network.route_wg.interface='wg'
  set network.route_wg.target='192.168.9.0'
  set network.route_wg.netmask='255.255.255.0'

  commit network
EOF

add_client() {
  ip=$1
  name=$2
  key=$3
uci -q batch <<-EOF > /dev/null
  delete network.wg_${name}
  set network.wg_${name}=wireguard_wg
  set network.wg_${name}.description='${name}'
  set network.wg_${name}.public_key='${key}'
  add_list network.wg_${name}.allowed_ips='${ip}/32'
  set network.wg_${name}.route_allowed_ips='1'
  set network.wg_${name}.persistent_keepalive '0'
  commit network
EOF
}

add_client 192.168.9.2  rtphone mV5wbW/tBw4ddIZgAL17dB0peTbqpcBGAmLOjNWDGSw=
add_client 192.168.9.3  rtlap   HWMn0MASsucG8NpcfxdFZtYjS2Vstw/LKgFmnpJGOQs=
add_client 192.168.9.9  s22     R3V784AbEqeaHQty6M1wgmDzhU1p6IT7ofsRgpYhFRQ=
add_client 192.168.9.10 goa     wqH/ZF11RKz6lUFF6qC5HgJjU/jziv9nWwcL2NnLTnk=

uci add_list network.wg_otg.allowed_ips='192.168.6.0/24'
uci commit network

exit 0
