#!/bin/sh

source /etc/secrets/env

cat > /etc/config/ddns.new << _DDNS_
config ddns 'global'
        option ddns_dateformat '%F %R'
        option ddns_loglines '250'
        option upd_privateip '0'

config service 'route53'
        option service_name 'route53-v1'
        option username '${AWS_ACCESS_KEY}'
        option password '${AWS_SECRET_KEY}'
        option use_https '0'
        option enabled '1'
        option lookup_host '${AWS_ROUTE53_ROUTERNAME}'
        option ip_source 'interface'
        option interface 'wan'
        option ip_interface 'pppoe-wan'
        option domain '${AWS_ROUTE53_DOMAIN_ID}'
        option force_interval '24'
        option retry_count '2'
_DDNS_

# uci commit

# /etc/init.d/ddns reload

exit 0
