#!/bin/sh

cat <<-EOF >/etc/config/firewall
config defaults 'defaults'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'DROP'

config include 'user'
        option path '/etc/firewall.user'

config include 'miniupnpd'
        option type 'script'
        option path '/usr/share/miniupnpd/firewall.include'
        option family 'any'
        option reload '1'

config zone
        option name 'lan'
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option masq_allow_invalid '1'
        option auto_helper '0'
        list network 'lan'
        list device 'bat0'
        list device 'br-lan'

config zone
        option name 'wan'
        option input 'DROP'
        option output 'ACCEPT'
        option forward 'DROP'
        option masq '1'
        option mtu_fix '1'
        option masq_allow_invalid '1'
        option auto_helper '0'
        list network 'wan'
        list network 'wan6'
        list device 'wan'

config forwarding
        option src 'lan'
        option dest 'wan'

config zone
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'
        option masq_allow_invalid '1'
        option auto_helper '0'
        list network 'modem'
        option name 'modem'
        option masq '1'

config forwarding
        option dest 'lan'
        option src 'modem'

config forwarding
        option src 'lan'
        option dest 'modem'

config rule
        option target 'ACCEPT'
        option src 'wan'
        option proto 'udp'
        option dest_port '547'
        option name 'Allow DHCPv6 (546-to-547)'
        option family 'ipv6'
        option src_port '546'

config rule
        option target 'ACCEPT'
        option src 'wan'
        option proto 'udp'
        option dest_port '546'
        option name 'Allow DHCPv6 (547-to-546)'
        option family 'ipv6'
        option src_port '547'

config redirect
        option target 'DNAT'
        option name 'lnd'
        list proto 'tcp'
        option src 'wan'
        option src_dport '9735'
        option dest 'lan'
        option dest_ip '192.168.2.20'
        option dest_port '9735'
EOF

uci commit firewall

exit 0
