#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='ap-living'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.2.7'
  commit network
EOF

exit 0
