#!/bin/sh

uci set 'network.@device[0].macaddr=00:14:4f:fc:07:01' || :
uci commit network || :

uci set 'wireless.@wifi-iface[0].macaddr=00:14:4f:fc:07:10' || :
uci set 'wireless.@wifi-iface[1].macaddr=00:14:4f:fc:07:11' || :
uci set 'wireless.@wifi-iface[2].macaddr=00:14:4f:fc:07:12' || :
uci set 'wireless.@wifi-iface[3].macaddr=00:14:4f:fc:07:13' || :
uci set 'wireless.@wifi-iface[4].macaddr=00:14:4f:fc:07:14' || :
uci set 'wireless.@wifi-iface[5].macaddr=00:14:4f:fc:07:15' || :
uci set 'wireless.@wifi-iface[6].macaddr=00:14:4f:fc:07:16' || :
uci set 'wireless.@wifi-iface[7].macaddr=00:14:4f:fc:07:17' || :
uci set 'wireless.@wifi-iface[8].macaddr=00:14:4f:fc:07:18' || :
uci set 'wireless.@wifi-iface[9].macaddr=00:14:4f:fc:07:19' || :
uci set 'wireless.@wifi-iface[10].macaddr=00:14:4f:fc:07:1a' || :
uci set 'wireless.@wifi-iface[11].macaddr=00:14:4f:fc:07:1b' || :
uci set 'wireless.@wifi-iface[12].macaddr=00:14:4f:fc:07:1c' || :
uci set 'wireless.@wifi-iface[13].macaddr=00:14:4f:fc:07:1d' || :
uci set 'wireless.@wifi-iface[14].macaddr=00:14:4f:fc:07:1e' || :
uci set 'wireless.@wifi-iface[15].macaddr=00:14:4f:fc:07:1f' || :

uci commit wireless || :
