#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='core-switch'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.2.6'
  del network.lan.ip6assign 
  commit network
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan6=interface
  set network.lan6.proto='dhcpv6'
  set network.lan6.ifname='@lan'
  set network.lan6.reqprefix='no'
  set network.lan6.peerdns='0'
  set network.lan6.delegate='0'
  set network.lan6.ip6ifaceid='::6'
  commit network
EOF

exit 0
