#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='dsl-router'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.2.1'
  commit network
EOF

uci -q batch <<-EOF >/dev/null
  set network.bat0=interface
  set network.bat0.proto='batadv'
  set network.bat0.ipaddr='192.168.3.1'
  set network.bat0.netmask='255.255.255.0'
  set network.bat0.routing_algo='BATMAN_IV'
  set network.bat0.ap_isolation=0
  set network.bat0.fragmentation=1
  set network.bat0.distributed_arp_table=1
  set network.bat0.gw_mode='on'
  commit network
EOF

exit 0
