#!/bin/sh

source /etc/secrets/env

uci -q batch <<-EOF >/dev/null
  delete network.wan
  delete network.wan6
  delete network.@switch[0]
  delete network.@switch_vlan[1]
  delete network.@switch_vlan[0]
 
  set network.switch=switch
  set network.switch.name='switch0'
  set network.switch.reset='1'
  set network.switch.enable_vlan='0'

  set network.switch_lan=switch_vlan
  set network.switch_lan.device='switch0'
  set network.switch_lan.vlan='1'
  set network.switch_lan.ports='0 1 2 4 6'
  set network.switch_lan.vid='1'

  set network.lan_eth0_1_dev.name='eth0'
  set network.lan.ifname='eth0'

  set network.dsl.annex=b
  set network.dsl.tone=b
  set network.dsl.xfer_mode=ptm
  set network.dsl.line_mode=vdsl
  set network.dsl.ds_snr_offset='-30'
  set network.dsl.firmware=/lib/firmware/vr9-b-dsl.bin

  set network.wan=interface
  set network.wan.proto='pppoe'
  set network.wan.ifname='dsl0.7'
  set network.wan.ipv6='auto'
  set network.wan.username='${telekom_user}'
  set network.wan.password='${telekom_pass}'
  set network.wan.keepalive=10
  set network.wan.macaddr='80:2A:A8:1E:86:A7'

  set network.wan_iptv=interface
  set network.wan_iptv.ifname='dsl0.8'
  set network.wan_iptv.proto='dhcp'
  set network.wan_iptv.ipv6='auto'
  set network.wan_iptv.macaddr='80:2A:A8:1E:86:A8'

  set network.wan6=interface
  set network.wan6.ifname='@wan'
  set network.wan6.proto='dhcpv6'
  set network.wan6.reqprefix='56'

  set network.lan.ip6assign=56

  commit network
EOF

uci -q batch <<-EOF >/dev/null
  set dhcp.@dnsmasq[0].domain=dhcp.home.measite.de
  set dhcp.@dnsmasq[0].local=/dhcp.home.measite.de/
  set dhcp.lan.start=100
  set dhcp.lan.limit=254
  set dhcp.lan.leasetime=24h
  add_list dhcp.lan.dhcp_option=6,192.168.2.7,192.168.2.8,192.168.2.5
  commit dhcp
EOF


exit 0
