#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='ffgateway'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  delete network.@switch_vlan[1]
  delete network.@switch_vlan[0]
  delete network.wan_dev
  set network.switch_vlan1=switch_vlan
  set network.switch_vlan1=switch_vlan
  set network.switch_vlan1.device='switch0'
  set network.switch_vlan1.vlan='1'
  set network.switch_vlan1.ports='0 1 2 3 4 6t'
  commit network
EOF


uci -q batch <<-EOF >/dev/null
  set network.lan.ipaddr='192.168.1.1'
  set network.wan.broadcast='192.168.2.255'
  set network.wan.dns='192.168.2.7 192.168.2.6 192.168.2.5'
  set network.wan.gateway='192.168.2.1'
  set network.wan.ipaddr='192.168.2.9'
  set network.wan.netmask='255.255.255.0'
  set network.wan.proto='static'
  commit network
EOF

exit 0
