#!/bin/sh

cat <<-EOF >/etc/config/firewall
config defaults
        option input 'ACCEPT'
        option output 'ACCEPT'
        option forward 'ACCEPT'

config include
        option path '/etc/firewall.user'

config zone
        option input 'ACCEPT'
        option forward 'ACCEPT'
        option output 'ACCEPT'
        option name 'lan'
        option network 'lan'

config zone
        option input 'ACCEPT'
        option output 'ACCEPT'
        option name 'wan'
        option forward 'ACCEPT'
        option network 'wan'

config forwarding
        option dest 'wan'
        option src 'lan'
EOF

uci commit firewall

exit 0
