BaseDir "/var/run/collectd"
PIDFile "/var/run/collectd.pid"
PluginDir "/usr/lib/collectd"
TypesDB "/usr/share/collectd/types.db"
Interval 30
ReadThreads 2

LoadPlugin cpu
<Plugin cpu>
        ValuesPercentage true
        ReportByCpu true
        ReportByState true
</Plugin>

LoadPlugin interface
<Plugin interface>
        IgnoreSelected false
        Interface "br-lan"
</Plugin>

LoadPlugin iwinfo

LoadPlugin load

LoadPlugin memory
<Plugin memory>
        ValuesPercentage false
        ValuesAbsolute true
</Plugin>

LoadPlugin rrdtool
<Plugin rrdtool>
        DataDir "/srv/rrd"
        RRARows 288
        RRASingle true
        RRATimespan 7200
        RRATimespan 86400
        RRATimespan 604800
        RRATimespan 2678400
        RRATimespan 31622400
</Plugin>
