#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set wireless.radio0.country=DE
  set wireless.radio0.channel=36
  set wireless.radio0.htmode='VHT80'
  set wireless.radio0.disabled=0
  set wireless.radio1.country=DE
  set wireless.radio1.channel=11
  set wireless.radio1.htmode='HT20'
  set wireless.radio1.disabled=0
  delete wireless.default_radio0
  delete wireless.default_radio1
  commit wireless
EOF

exit 0
