#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set system.@system[0].hostname='ap-max'
  commit system
EOF

uci -q batch <<-EOF >/dev/null
  set network.lan6=interface
  set network.lan6.proto='dhcpv6'
  set network.lan6.ifname='@lan'
  set network.lan6.reqprefix='no'
  set network.lan6.peerdns='0'
  set network.lan6.delegate='0'
  commit network
EOF

uci -q batch <<-EOF >/dev/null
  add_list network.@device[0].ports='wan'
  set network.lan.ipaddr='192.168.2.3'
  set network.lan.macaddr='0C:80:63:F7:1F:76'
  add_list network.lan.dns='192.168.2.3'
  add_list network.lan.dns='192.168.2.7'
  add_list network.lan.dns='192.168.2.6'
  del network.lan.ip6assign
  commit network
EOF

exit 0
