#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set wireless.radio1.country=DE
  set wireless.radio1.channel=36
  set wireless.radio1.disabled=0
  set wireless.radio1.htmode='HE80'
  set wireless.radio1.cell_density=0
  set wireless.radio1.beacon_int=50
  set wireless.radio0.country=DE
  set wireless.radio0.channel=8
  set wireless.radio0.htmode='HE40'
  set wireless.radio0.cell_density=0
  set wireless.radio0.disabled=0
  set wireless.radio0.beacon_int=500
  set wireless.radio0.txpower='12'
  delete wireless.default_radio0
  delete wireless.default_radio1
  commit wireless
EOF

exit 0
