#!/bin/sh

uci -q batch <<-EOF >/dev/null
  set dhcp.@dnsmasq[0].domain=home.measite.de
  set dhcp.@dnsmasq[0].local=/home.measite.de/
  set dhcp.lan.start=100
  set dhcp.lan.limit=254
  set dhcp.lan.leasetime=24h
  add_list dhcp.lan.dhcp_option=6,192.168.2.7,192.168.2.6,192.168.2.5
  add_list dhcp.lan.dhcp_option=26,1492
  commit dhcp
EOF

static_lease() {
  name=$1
  mac=$2
  ip=$3
  section=$(echo "${name}"|tr '-' '_')
uci -q batch <<-EOF >/dev/null
  set dhcp.${section}=host
  set dhcp.${section}.name=${name}
  set dhcp.${section}.mac=${mac}
  set dhcp.${section}.ip=${ip}
  commit dhcp
EOF
}

static_lease 'hue-gateway'        '00:17:88:a6:55:32' '192.168.2.30'

static_lease 'power-aquarium'     'ac:84:c6:59:ca:9f' '192.168.2.31'
static_lease 'power-tv-a'         '50:c7:bf:0b:90:e8' '192.168.2.32'
static_lease 'power-tv-b'         '50:c7:bf:0b:88:3b' '192.168.2.33'
static_lease 'power-outdoor'      '50:c7:bf:0b:8b:b0' '192.168.2.34'
static_lease 'power-kuehlschrank' '50:c7:bf:0b:8d:27' '192.168.2.35'
static_lease 'power-3d-druck'     '50:c7:bf:28:bd:d9' '192.168.2.36'

static_lease 'harmonyhub'         'c8:db:26:07:09:c2' '192.168.2.49'
static_lease 'chromecast-living'  '54:60:09:fc:0f:68' '192.168.2.50'

static_lease 'firetv'             'f0:27:2d:18:1a:6c' '192.168.2.80'
static_lease 'printer'            'b4:b5:2f:f5:86:7c' '192.168.2.81'

exit 0
